### ISSUE TITLE
integrate Arok Wolvengrey's "Cree: Words" dictionary

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/dictionary-database#9]
- [x] ask Arok for documentation of the fields in his Toolbox database
- [x] convert Toolbox file to JSON
- [x] write script to clean / normalize the CW JSON data for the ALTLab database (#12)

Notes on this database have now been moved here:

* issue branch: https://github.com/UAlbertaALTLab/dictionary-database/blob/clean-wolvengrey/docs/CW.md
* main branch: https://github.com/UAlbertaALTLab/dictionary-database/blob/main/docs/CW.md

**Comment by aarppe** [comment]
Notes:

1. In the TSV solution, multiple occurrences of the same field are combined into one, with the parts delimited with a double semi-colon surrounded by spaces, i.e. '` ;; `'.
2. The presumption for needing an FSTSTEM is if the CW stem is not a genuine prefix for the CW lemma (with the potential removal of the stem-final -w), i.e. removal of the stem string from the lemma a) either leaves some prefixal as well as suffixal segment, b) or does not succeed at all, due to some rarer morphophonological change.
3. For the most part, we can create in a straight-forward manner the derivational breakdown based on the current TSV formatting. It is only when Arok provides altenative decompositions that a more structured representation of the morphological breakdown will be needed.

**Comment by eddieantonio** [comment]
> * The definitions include cross-references in the data, e.g. `[see êkwa]`. These cross-references should be extracted into their own field in the database, but reintegrated for purposes of rendering in Itwêwina.

This should absolutely _stay_ as a seperate field! So that definitions can reference other heads. Would [`DatabaseReference `](https://format.digitallinguistics.io/schemas/DatabaseReference.html) be the correct type for this?

> * Stem-internal morphological information is currently conflated into a single field, delimited by semicolons or some such. Parsing the stem-internal morphology would enable a derivational version of the analyzer.

YES! Let's maintain this as separate data in the database!

**Comment by dwhieb** [comment]
> This should absolutely stay as a seperate field! So that definitions can reference other heads. Would DatabaseReference be the correct type for this?

Great! Most dictionary database software treats cross-references (_see X_) as a kind of lexical relation (along with synonyms, antonyms, etc.), so DaFoDiL does the same, using a DatabaseReference object: `Lexeme/lexicalRelations/DatabaseReference`.

**Comment by dwhieb** [comment]
Closed by cda303578aa6d7cb3e308d51bc2875c199e7c53c.
